### ISSUE TITLE
MODULES(lzo) had to be added

### ISSUE THREAD

**Issue by tomjtoth** [arcmags/ramroot#11]
Hello,

No idea if it's related to my setup only, but I had to add lzo to the MODULES() in /etc/mkinitcpio.conf yesterday and re-run mkinitcpio -P again to get it to work 

Feel free to dismiss this if it's a false alarm, otherwise I suggest modprobe lzo along with zram in the hook, I spent quite a few hours to track this down, no idea why I didn't simply modify your hook too, perhaps I will later.

BR,
Tamás

**Comment by tomjtoth** [comment]
ohh looks like [this one ](https://github.com/arcmags/ramroot/issues/10 )is related, please consider including something like 
if ! $(lsmod | grep -Pq '\blzo\b'); then
  modprobe lzo
fi

in your hook

**Comment by brezoi** [comment]
Maybe lz4 could be used instead of lzo, since it is in the default kernel? I fixed mine with the same procedure as tomjtoth. Thanks for the project, very useful.

**Comment by brezoi** [comment]
Submitted a pull request from my fork that switches it to lz4. Not sure if it will be accepted, but feel free to try it, simple modification to the hook. See https://github.com/arcmags/ramroot/pull/12/files or try https://github.com/brezoi/ramroot to test.

**Comment by brezoi** [comment]
Updated my fork and therefore pull request to just use the default compression of the system, which just means dropping the -a option in zramctl call. I then spit out which encryption is being used, which could be taken out if so desired. This should work on older and newer kernels, and help when trying it outside of archlinux.

**Comment by arcmags** [comment]
Thanks for looking into this, guys.  I'm currently out of town, but should be able to update github and the AUR package within a few days.

**Comment by tomjtoth** [comment]
I didn't have the time to dig deeper but on my setup simply omitting the "-a lzo" part in the hook somehow still produces an error, I'll investigate further next weekend.
I remember it failed with "-a lz4" before I inserted lzo in MODULES and ran mkinitcpio -P
something funny is going on there because last time (re-installed my thumbdrive) not even that solved the problem

**Comment by brezoi** [comment]
Hello again, I got a chance to do some testing and here's the nutshell:

- With a base install, kernel 5.7.4-arch1-1, ramroot as packaged on the AUR fails as expected.

- I tried manually creating zram devices with zramctl after booting normally and they worked. The lzo-rle module was automatically loaded after zram was loaded, because lzo-rle is the default in /sys/block/zram0/comp_algorithm. Not sure how lz4 was mixed in before???

- I made modifications to the hook, to attempt to _modprobe lzo-rle_ but it failed during boot, with error: _Module lzo-rle not found in /lib/modules/5.7.4-arch1-1_

- Then I added lzo-rle to MODULES() in /etc/mkinitcpio.conf and ramroot worked successfully. Just like the first solution.

- So from my observations, it seems the the modules for zram compression are loaded eventually, but not when ramroot is trying to use them. This is some sort of change with the packaging of the latest kernel, as lzo worked before, and would still work if loaded in MODULES() with the current release of ramroot.

- It still should be possible to omit the -a in the zramctl call, but seems a chicken / egg problem, because the specific module has to be loaded before the hook is run.

- Going to cancel my pull request, because it is not really any sort of fix. Hope this helps. If I find time, I'll keep messing with it.

Take care.

**Comment by brezoi** [comment]
I noticed that when I ran _zramctl -f -s 100M -a lz4_ on a regular boot, it worked without adding a module other than zram. So I modded the hook again, and just switched it to _zramctl -f -s  ${zram}M -a lz4_ and it worked. Of course, you have to regular boot, edit the hook, remove all the MODULES=() entries from _/etc/mkinitcpio.conf_, run _mkinitcpio -P_ and reboot. I'm curious why that didn't work for you tomjtoh. 
![Screenshot_archlinux_2020-06-24_08:26:08](https://user-images.githubusercontent.com/13857369/85556054-7c489280-b5f4-11ea-9dbb-55bd40292508.png)

**Comment by brezoi** [comment]
From my tests, only lz4 and zstd work. Trying -a for lzo, lzo-rle, lz4hc and 842 fail.

**Comment by tomjtoth** [comment]
I successfully booted into RAM while not doing any modification since the last try. I'm quite sure I messed up something or remembered something wrong. Will experiment now, and edit this comment when lz4 boot succeeds. 

(Does the nvidia driver have any effect on that early hooks? I tihnk it only blacklists nouveau)
(btw I also simply mount my root partition to /mnt and arc-chroot into it - I guess `mkinitcpio -P` should work equally well as during installation of arch, maybe I should have unmounted /mnt between those reboots? will try to remember that now)

 - `cat /usr/lib/initcpio/hooks/ramroot | grep zramct
    zram_device=$(zramctl -f -s ${zram}M)`
 - restored `MODULES=()` in `/etc/mkinitcpio.conf` and ran `mkinitcpio -P`
 - rebooted and no success:
 - `grep -R . /sys/module/zswap/parameters/
/sys/module/zswap/parameters/same_filled_pages_enabled:Y
/sys/module/zswap/parameters/enabled:Y
/sys/module/zswap/parameters/max_pool_percent:20
/sys/module/zswap/parameters/compressor:lz4
/sys/module/zswap/parameters/zpool:z3fold
/sys/module/zswap/parameters/accept_threshold_percent:90`
 - from journalctl: `kernel: zram: Cannot initialise **lzo-rle** compressing backend`

So for some reason (they became default during the kernel update?) lz4 and z3fold are loaded but `zramctl -f -s ${zram}M` wants to use lzo-rle


Upon adding the `-a lz4` to the hook I get:
 - `grep -R . /sys/module/zswap/parameters/
/sys/module/zswap/parameters/same_filled_pages_enabled:Y
/sys/module/zswap/parameters/enabled:Y
/sys/module/zswap/parameters/max_pool_percent:20
/sys/module/zswap/parameters/compressor:lz4
/sys/module/zswap/parameters/zpool:z3fold
/sys/module/zswap/parameters/accept_threshold_percent:90`
 - `journalctl | grep lz
jún 27 14:07:08 k128 kernel: zswap: loaded using pool lz4/z3fold
jún 27 14:07:08 k128 kernel: zram: Cannot initialise lzo-rle compressing backend`

for some reason the lzo-rle is still wanted
reading https://wiki.archlinux.org/index.php/Zswap#Compression_algorithm says

`There is no issue setting the compression to lz4 at runtime using sysfs or via systemd-swap but zswap starts in this case with lzo and switches at a later stage to lz4. To use zswap with lz4 straight away, this must be defined in the kernel boot parameter and the lz4 module must be loaded early by the kernel. This can be achieved by following these steps:

    Add lz4 lz4_compress to the mkinitcpio#MODULES array.
    Replace the ramdisk environment with a newly generated one:

    # mkinitcpio -g /boot/initramfs.img

    Add zswap.compressor=lz4 to your kernel parameters.`

I believe I have to add lz4 and lz4-compress to MODULES=()
(OR lzo OR lzo-rle and I could drop the `-a tag`?)

I dropped the `-a tag` and it works without the ugly kernel parameters as well (lz4/z3fold), now trying to move those MODULES=(lz4 lz4-compress) into the hook

that didn't work out, with MODULES=():

 first I tried in the hook:`echo lz4 > /sys/module/zswap/parameters/compressor
echo z3fold > /sys/module/zswap/parameters/zpool
echo 1 > /sys/module/zswap/parameters/enabled
echo 20 >  /sys/module/zswap/parameters/max_pool_percent`


then `modprobe lz4 lz4-compress`
I suppose it's 2 differentthings to:
 - run `mkinitcpio -P` with  `MODULES=(lz4 lz4-compress)`
 - or `modprobe lz4 lz4-compress` with a `MODULES=()` boot

anyways, I guess I'm back to square one, I have to run `mkinitcpio -P` with  `MODULES=(lz4 lz4-compress)`
 

<after a few hours break>

I cannot put my finger on it, but I have a feeling the super-slow thumbdrive has something to do with the success rate of my experimenting, I started using `sync -f /` before reboot - I think linux would wait anyways for the data to get written physically to the storage device, but I'm no expert, just poking around.



I now have `MODULES=(lz4 lz4_compress)` and I do need the `-a lz4` in the hook. Otherwise booting to RAM fails
Not sure if I have the energy to experiment more with this...

**Comment by brezoi** [comment]
Hello tomjtoth, sorry for your issues with this. Since you cannot get it to work without specifying a module, I would suggest this:

Reset to MODULES=(), then edit /usr/lib/initcpio/hooks/ramroot line we all love to _zram_device=$(zramctl -f -s ${zram}M -a lz4)_, then run _mkinitcpio -P_, and try booting. If that doesn't work you can usually see an error on the screen while booting, for a nanosecond. It would be nice to see the error it spits, so you could add a _sleep 60_ on the line below the command, so the screen doesn't disappear, and get the error zramctl shows. This works great on my VM, but you might be right about slow storage and other hardware stuff.

Also, I have code on my fork that tries all the algorithms, in the order lzo-rle, lz4, lzstd, lzo. If you want to try it out, replace your copy of the hook with https://github.com/brezoi/ramroot/blob/master/usr/lib/initcpio/hooks/ramroot, and then run _mkinitcpio -P_ It's proposed as a pull request here, so if you like, you can comment on your success/failure there.

Best of luck.

**Comment by arcmags** [comment]
lzo is now explicitly chosen with version 2.0.2
