### ISSUE TITLE
System not loaded to RAM even if default is Y

### ISSUE THREAD

**Issue by olm52** [arcmags/ramroot#17]
It seems that in some updated archlinux systems recently, even if in the configuration file 
_ps_default=yes_
at boot there is the message:

_Load root file system to zram [Y/n]
zramctl: /dev/zram0: failed to reset: Device or resource busy
===> FAILED: error initializing the device_

After few seconds the system will boot to normal mode.
Available RAM is not the case here.

Typing Y and ENTER will boot correctly to RAM but this is not automatic.

**Comment by paretoaudio** [comment]
PROBLEM: The following message is seen at boot with ramroot enabled.
**Load root file system to zram [Y/n]
zramctl: /dev/zram0: failed to reset: Device or resource busy ===> FAILED: error initializing the device__**

CAUSE: The problem is caused by interrupting the ramroot copy process while it is running by long-pressing the power button to reset the machine. At the next boot when prompted for "ramroot Y/N" no answer will raise an error and then default to the no ramroot path. Other than timing out, one can simulate this by entering any character at the prompt like 'd' NOT followed by an enter key. Hitting the enter key will take the "happy path" and no error will happen.

SYMPTOM: Once the ramroot process is interrupted in this way, it will take the error path to no ramroot at every boot until fixed. 

CURE: To fix it, force it to the "happy path" by simply entering the enter key or 'y' followed by enter key at the prompt. Let it successfully boot in ram. There after the system will take the default after the timeout period as expected.

Strangely the solution does not seem to persist on disk.  One machine was fixed as described above. Next the same USB drive was moved to a different machine and the problem occurred again on first boot. It then was fixed and the fix persisted on subsequent boots. Unfortunately on some machines the cure does not persist.

The ramroot.conf on the machines in question have the default and timeout set correctly.

It is likely this is the underlying issue with the unresponsive keyboard problem that use to happen in this same piece of code..

This problem happens with or without a GPU card installed and on both AMD and Intel machines.
